-- Monitor layout & persistent workspace rules — PORTABLE default.
--
-- No monitor names are hardcoded, so this works out of the box on ANY machine:
-- every connected display comes up at its preferred mode (the output=""
-- rule below) and workspaces stay on the focused/output monitor.
--
-- The Lotus reference build's exact dual-monitor layout
-- (DP-2 @1440p primary + HDMI-A-1 @1080p secondary, custom positions/scales,
-- persistent workspaces 1-10) lives in monitors.lotus.lua and is swapped in
-- automatically by install-scripts/06-dotfiles.sh when both connectors are
-- physically connected. You can also apply it manually:
--   cp $HOME/.config/hypr/monitors.lotus.lua $HOME/.config/hypr/monitors.lua
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
