-- Generated by nwg-displays on 2026-09-07 at 23:43:28. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "2560x360",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "DP-2",
    mode = "2560x1440@165.0",
    position = "0x0",
    scale = 1,
    vrr = 0
})
