-- Generated by nwg-displays on 2026-07-27 at 03:34:41. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-2",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "HDMI-A-1",
    default = true
})
hl.workspace_rule({
    workspace = "4",
    monitor = "HDMI-A-1"
})
