#!/usr/bin/env bash
# PersonaPalette.sh — Sync Persona-Quickshell colors with the LOTUS palette
# Regenerates Data/Colors.qml from colors.conf. Quickshell hot-reloads it.
# Safe no-op when the Persona theme isn't installed.

set -euo pipefail

PQ="$HOME/.config/quickshell/Persona-Quickshell"
PAL="$HOME/.config/lotus-palette/colors.conf"
BASE="$PQ/Data/Colors.base.qml"   # pristine upstream copy (reference only)
OUT="$PQ/Data/Colors.qml"

[[ -d "$PQ" && -f "$PAL" && -f "$OUT" ]] || exit 0

# Snapshot the pristine upstream singleton once, so future re-themes of the
# repo can always diff against the original values
[[ -f "$BASE" ]] || cp "$OUT" "$BASE"

get() { grep "^$1=" "$PAL" | head -1 | cut -d= -f2 | tr 'a-f' 'A-F'; }

BG=$(get bg)             ; BG=${BG:-#141218}
FG=$(get fg)             ; FG=${FG:-#D8D0E8}
PRIMARY=$(get primary)   ; PRIMARY=${PRIMARY:-#C4A8E2}
PRIMARY_L=$(get primary_light); PRIMARY_L=${PRIMARY_L:-$PRIMARY}

C0=$(get bg_alt)     ; C0=${C0:-$BG}
C1=$(get red)        ; C1=${C1:-#C8B8C8}
C2=$(get green)      ; C2=${C2:-#C0D0C0}
C3=$(get amber)      ; C3=${C3:-#D8C8D0}
C5=$(get magenta)    ; C5=${C5:-#D0B8D0}
C6=$(get cyan)       ; C6=${C6:-#B8C0D0}
C8=$(get gray)       ; C8=${C8:-#585060}
C9=$(get rose)       ; C9=${C9:-#D8C0D0}
C10=$(get mint)      ; C10=${C10:-#B8D8C0}
C11=$(get neon_yellow); C11=${C11:-#E8E0D0}
C13=$(get lavender)  ; C13=${C13:-#C8B8D8}
C14=$(get neon_cyan) ; C14=${C14:-#D0E0E8}

cat > "$OUT" <<EOF
pragma Singleton
import Quickshell
import QtQuick

Singleton {
    id: root

    // ── GENERATED by PersonaPalette.sh from ~/.config/lotus-palette/colors.conf ──
    // Do not edit by hand: run PersonaPalette.sh or change your LOTUS palette.
    // Pristine upstream version preserved in Colors.base.qml

    // Pywal16 colors
    readonly property string background: "$BG"
    readonly property string foreground: "$FG"
    readonly property string cursor: "$FG"

    // Standard 16 colors
    readonly property string color0: "$C0"
    readonly property string color1: "$C1"
    readonly property string color2: "$C2"
    readonly property string color3: "$C3"
    readonly property string color4: "$PRIMARY"
    readonly property string color5: "$C5"
    readonly property string color6: "$C6"
    readonly property string color7: "$FG"
    readonly property string color8: "$C8"
    readonly property string color9: "$C9"
    readonly property string color10: "$C10"
    readonly property string color11: "$C11"
    readonly property string color12: "$PRIMARY_L"
    readonly property string color13: "$C13"
    readonly property string color14: "$C14"
    readonly property string color15: "$PRIMARY_L"

    // Named aliases
    readonly property string black: color0
    readonly property string red: color1
    readonly property string green: color2
    readonly property string yellow: color3
    readonly property string blue: color4
    readonly property string magenta: color5
    readonly property string cyan: color6
    readonly property string white: color7
    readonly property string brightBlack: color8
    readonly property string brightRed: color9
    readonly property string brightGreen: color10
    readonly property string brightYellow: color11
    readonly property string brightBlue: color12
    readonly property string brightMagenta: color13
    readonly property string brightCyan: color14
    readonly property string brightWhite: color15
}
EOF

echo "Persona palette synced."
