# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates
# windowrule = opacity 1.0 override 1.0 override, match:class ^(zen)$
windowrule = workspace special:silent, match:class ^(asm-gui)$
#windowrule = opacity 1.0 override 1.0 override, match:title (.*YouTube.*)

# Default workspaces (DP-2: 1-5, HDMI-A-1: 6-10)
windowrule = workspace 6, match:class ^(discord)$
windowrule = workspace 7, match:class ^(com\.obsproject\.Studio)$
windowrule = workspace 7, match:title ^(Arctis Sound Manager)$
windowrule = workspace 7, match:class ^(org\.rncbc\.qpwgraph)$
windowrule = workspace 2, match:class ^(zen|zen-alpha)$
windowrule = workspace 1, match:class ^([Ss]team)$
windowrule = workspace 1, match:class ^(steam_app_\d+)$
windowrule = workspace 1, match:class ^(Wuthering Waves|WutheringWaves|Wuthering_Waves|Client-Win64-Shipping|helldivers2|Helldivers2|Warframe|Soulframe)$
windowrule = workspace 3, match:class ^(kitty)$
windowrule = workspace 4, match:class ^([Tt]hunar)$
windowrule = workspace 4, match:class ^(xarchiver)$
windowrule = workspace 5, match:class ^([Ss]potify)$
windowrule = workspace 5, match:class ^(mpv)$
windowrule = workspace 5, match:class ^(swappy)$
windowrule = workspace 6, match:class ^(vesktop)$
windowrule = workspace 8, match:class ^(net\.lutris\.Lutris|protontricks|winetricks)$
windowrule = workspace 9, match:class ^(gnome-system-monitor|org\.gnome\.SystemMonitor|nvidia-settings)$
windowrule = workspace 10, match:class ^(openrgb|org\.openrgb\.OpenRGB|Vial|vial|org\.freedesktop\.Piper|com\.leinardi\.gwe)$

# Waybar layer rule for HyprGlass
layerrule = match:namespace waybar, blur on
layerrule = match:namespace waybar, ignore_alpha 0.05
