[Lotus Purple]
# === Backgrounds ===
main               = 141218
main-elevated      = 1C1A22
sidebar            = 141218
player             = 141218
card               = 1C1A22
shadow             = 000000

# === Text ===
text               = D8D0E8
subtext            = 887898

# === Highlights & Selection ===
highlight          = 1C1A22
highlight-elevated = 282430
selected-row       = C4A8E2

# === Buttons ===
button             = C4A8E2
button-active      = D8D0E8
button-disabled    = 383048
tab-active         = 383048

# === Notifications & Misc ===
notification       = 8C7AA6
notification-error = C8B8C8
misc               = 504860
