#!/usr/bin/env bash
# apply-from-wallpaper.sh
# Regenera colors.conf desde el material palette del wallpaper (colors.json)
# y reaplica LOTUS (UserDecorations, wallust/hyprlock, ghostty, rofi, gtk, wlogout).
# Llamado desde switchwall.sh post_process en cada cambio de fondo.

set -euo pipefail

STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/quickshell/user/generated"
PALETTE="$HOME/.config/lotus-palette/colors.conf"
APPLY="$HOME/.config/lotus-palette/apply-colors.sh"

[[ -f "$STATE_DIR/colors.json" ]] || { echo "[lotus] colors.json no encontrado"; exit 0; }

get() { jq -r --arg k "$1" '.[$k] // empty' "$STATE_DIR/colors.json"; }

{
    echo "# Auto-generated by apply-from-wallpaper.sh (sigue el wallpaper)"
    echo "primary=$(get primary)"
    echo "primary_dim=$(get secondary)"
    echo "primary_dark=$(get secondary_container)"
    echo "primary_light=$(get tertiary)"
    echo "bg=$(get background)"
    echo "bg_alt=$(get surface_container)"
    echo "bg_light=$(get surface_container_high)"
    echo "fg=$(get on_background)"
    echo "fg_dim=$(get on_surface_variant)"
    echo "border=$(get outline_variant)"
    echo "border_light=$(get outline)"
    echo "red=$(get term1)"
    echo "green=$(get term2)"
    echo "yellow=$(get term3)"
    echo "blue=$(get term4)"
    echo "magenta=$(get term5)"
    echo "cyan=$(get term6)"
    echo "coral=$(get term9)"
    echo "teal=$(get term6)"
    echo "amber=$(get term3)"
    echo "indigo=$(get term4)"
    echo "lavender=$(get term13)"
    echo "fuchsia=$(get term5)"
    echo "orange=$(get term9)"
    echo "neon_green=$(get term10)"
    echo "neon_cyan=$(get term14)"
    echo "neon_pink=$(get term13)"
} > "$PALETTE"

bash "$APPLY" >/tmp/lotus-apply.log 2>&1 || echo "[lotus] apply-colors.sh fallo (log: /tmp/lotus-apply.log)"