monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-SteelSeries_SteelSeries_Arctis_Nova_5-00"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
