monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "Arctis_Game"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1000
      }
    }
  }
  {
    matches = [
      {
        node.name = "Arctis_Media"
      }
    ]
    actions = {
      update-props = {
        priority.session = 500
      }
    }
  }
  {
    matches = [
      {
        node.name = "Arctis_Chat"
      }
    ]
    actions = {
      update-props = {
        priority.session = 500
      }
    }
  }
  {
    matches = [
      {
        node.name = "effect_output.sonar-micro-eq"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1000
      }
    }
  }
]
