# Custom Preset — Yellowstone
purple=#EDCE5E
purple_dim=#B7992D
purple_dark=#5F511F
bg=#100E08
bg_alt=#221E10
fg=#E5DCBC
fg_dim=#A59559
red=#59ADF1
green=#4CD3E5
cyan=#4CBAE5
orange=#424AEF
pink=#5EED6F
yellow=#8F3DF4
blue=#C151E0
border=#594E26

