# D̷E̷D̷S̷E̷C̷ Hyprland Colors

$background = rgb(141218)
$foreground = rgb(D8D0E8)
$color0 = rgb(141218)
$color1 = rgb(C8B8C8)
$color2 = rgb(B8B0C8)
$color3 = rgb(E0D8E8)
$color4 = rgb(B8B8D0)
$color5 = rgb(D0B8D0)
$color6 = rgb(B8C0D0)
$color7 = rgb(cccccc)
$color8 = rgb(383048)
$color9 = rgb(C8B8C0)
$color10 = rgb(B8D0C8)
$color11 = rgb(D8C8D0)
$color12 = rgb(9080A8)
$color13 = rgb(C8B8D8)
$color14 = rgb(D8D0E8)
$color15 = rgb(cccccc)
