# LOTUS Palette — Randomized
primary=#3C1201
primary_dim=#B75B2D
primary_dark=#5F351F
primary_light=#EFC0A8
bg=#000000
bg_alt=#221610
bg_light=#2F231C
fg=#E9D3C7
fg_dim=#A57259
border=#593726
border_light=#784E3A
red=#42EFEF
orange=#4299EF
yellow=#3D3DF4
coral=#5EC9ED
amber=#2A5BED
peach=#B1E895
rose=#62E8BC
green=#36E2A8
teal=#1FDFAF
cyan=#36E2C5
sky=#5199E0
blue=#6951E0
indigo=#9B2CD2
mint=#9BE084
magenta=#EA47B4
lavender=#E29CCA
violet=#C13BDC
fuchsia=#7F4CE5
plum=#BF3F55
neon_green=#1FF9B0
neon_cyan=#1FF9D4
neon_pink=#7AF43D
neon_yellow=#1F1FF9
gray=#897C75
slate=#756056
stone=#808064
ash=#504B48

