# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates
# windowrule = opacity 1.0 override 1.0 override, match:class ^(zen)$
windowrule = workspace special:silent, match:class ^(asm-gui)$
#windowrule = opacity 1.0 override 1.0 override, match:title (.*YouTube.*)

# Default workspaces (DP-2: 1-5, HDMI-A-1: 6-10)
windowrule = workspace 6, match:class ^(discord)$
windowrule = workspace 7, match:class ^(com\.obsproject\.Studio)$
windowrule = workspace 7, match:title ^(Arctis Sound Manager)$
windowrule = workspace 7, match:class ^(org\.rncbc\.qpwgraph)$
windowrule = workspace 1, match:class ^([Ss]team)$

# Waybar layer rule for HyprGlass
layerrule = match:namespace waybar, blur on
layerrule = match:namespace waybar, ignore_alpha 0.05
